# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='api_key',
            new_name='account_key',
        ),
    ]
