# Generated by Django 3.2 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='github_repo',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
